export interface AchievementCatalogEntry {
  id: string;
  emoji: string;
  respects: number;
  maxProgress: number;
}

export const ALL_ACHIEVEMENTS: AchievementCatalogEntry[] = [
  { id: "not_rubbed_yet", emoji: "🤏", respects: 33, maxProgress: 10 },
  { id: "half_hundred", emoji: "🌟", respects: 50, maxProgress: 1 },
  { id: "diary", emoji: "📆", respects: 50, maxProgress: 31 },
  { id: "golden_hundred", emoji: "💯", respects: 90, maxProgress: 100 },
  { id: "skillful_hands", emoji: "💪", respects: 100, maxProgress: 100 },
  { id: "early_bird", emoji: "🌅", respects: 135, maxProgress: 20 },
  { id: "lightning", emoji: "⚡", respects: 200, maxProgress: 1 },
  { id: "sniper", emoji: "🎯", respects: 211, maxProgress: 5 },
  { id: "deja_vu", emoji: "🔄", respects: 222, maxProgress: 2 },
  { id: "speedrunner", emoji: "⏱️", respects: 222, maxProgress: 5 },
  { id: "midnight_puller", emoji: "☠️", respects: 222, maxProgress: 10 },
  { id: "rounder", emoji: "🔟", respects: 228, maxProgress: 6 },
  { id: "everest", emoji: "🏔️", respects: 228, maxProgress: 61 },
  { id: "mariana_trench", emoji: "🕳️", respects: 228, maxProgress: 0 },
  { id: "number_collector", emoji: "🔢", respects: 233, maxProgress: 5 },
  { id: "day_equals_size", emoji: "📅", respects: 300, maxProgress: 0 },
  { id: "solid_thousand", emoji: "💰", respects: 333, maxProgress: 1000 },
  { id: "bull_trend", emoji: "📈", respects: 333, maxProgress: 5 },
  { id: "bear_market", emoji: "📉", respects: 333, maxProgress: 5 },
  { id: "traveler", emoji: "🗺️", respects: 500, maxProgress: 61 },
  { id: "freeze", emoji: "❄️", respects: 555, maxProgress: 5 },
  { id: "five_k", emoji: "💎", respects: 700, maxProgress: 5000 },
  { id: "oldtimer", emoji: "🗓️", respects: 700, maxProgress: 3 },
  { id: "anniversary", emoji: "🎂", respects: 700, maxProgress: 365 },
  { id: "contrast_shower", emoji: "🚿", respects: 777, maxProgress: 0 },
  { id: "pythagoras", emoji: "📐", respects: 777, maxProgress: 1 },
  { id: "leet_speak", emoji: "💻", respects: 777, maxProgress: 1 },
  { id: "moscovite", emoji: "🏙️", respects: 800, maxProgress: 5 },
  { id: "hour_precision", emoji: "🕐", respects: 888, maxProgress: 0 },
  { id: "wonder_stranger", emoji: "💋", respects: 900, maxProgress: 500 },
  { id: "valentine", emoji: "💝", respects: 999, maxProgress: 1 },
  { id: "new_year_gift", emoji: "🎄", respects: 999, maxProgress: 1 },
  { id: "mens_solidarity", emoji: "🤝", respects: 999, maxProgress: 1 },
  { id: "friday_13th", emoji: "☠️", respects: 999, maxProgress: 1 },
  { id: "leap_cock", emoji: "📅", respects: 999, maxProgress: 1 },
  { id: "turtle", emoji: "🐌", respects: 1000, maxProgress: 10 },
  { id: "golden_cock", emoji: "👑", respects: 1000, maxProgress: 10000 },
  { id: "sum_of_previous", emoji: "🎲", respects: 1000, maxProgress: 0 },
  { id: "bazooka_hands", emoji: "💥", respects: 1222, maxProgress: 1000 },
  { id: "triple", emoji: "🎰", respects: 1333, maxProgress: 3 },
  { id: "veteran", emoji: "🗓️", respects: 1333, maxProgress: 5 },
  { id: "minute_precision", emoji: "⏰", respects: 1333, maxProgress: 0 },
  { id: "poker", emoji: "🎴", respects: 1777, maxProgress: 4 },
  { id: "keeper", emoji: "🗓️", respects: 1888, maxProgress: 10 },
  { id: "cosmic_cock", emoji: "🚀", respects: 2000, maxProgress: 20000 },
  { id: "maximalist", emoji: "🔝", respects: 2000, maxProgress: 10 },
  { id: "diamond_hands", emoji: "💎", respects: 2222, maxProgress: 7 },
  { id: "diamond_eye", emoji: "💎", respects: 2222, maxProgress: 5 },
  { id: "greek_myth", emoji: "⚡", respects: 2222, maxProgress: 30000 },
  { id: "fibonacci_father", emoji: "🔢", respects: 2222, maxProgress: 9 },
  { id: "annihilator_cannon", emoji: "☢️", respects: 2222, maxProgress: 5000 },
];
