FROM oven/bun:1.3.9-debian

WORKDIR /workspace

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    git \
    ca-certificates \
    curl \
    wget \
    bash \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

RUN groupadd --gid 1000 devuser \
    && useradd --uid 1000 --gid devuser --shell /bin/bash --create-home devuser

USER devuser

CMD ["sleep", "infinity"]
